# Deployment

replicaCount: 2

terminationGracePeriodSeconds: "30"

image:
  repository: ghcr.io/naqa92/todolist
  tag: "0.1.5"
  pullPolicy: IfNotPresent
  imagePullSecrets: []
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

env: {}

env_secrets:
  - name: DATABASE_URL
    secretName: "db-app"
    secretKey: "uri"

port: 5000

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  timeoutSeconds: 5

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 5

startupProbe: {}

lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "sleep 15"] # Délai avant SIGTERM pour finir les requêtes en cours

# Service

service:
  enabled: true
  type: ClusterIP
  port: 5000
  targetPort: 5000

# Ingress

ingress:
  enabled: true
  className: "nginx"
  host: todolist.127.0.0.1.nip.io
  annotations: {}
  tls: []
