version: "3"

tasks:
  cluster-create:
    desc: Crée un kind cluster et déploie l'application
    vars:
      TIMEOUT: 300s
    cmds:
      - task: cluster-create-kind
      - task: wait-cluster-ready
      - task: install-ingress-nginx
      - task: deploy-app
      - echo "Déploiement OK!"

  cluster-create-kind:
    desc: Creates a kind cluster
    cmds:
      - cmd: kind create cluster --config kind.yaml
    internal: true

  wait-cluster-ready:
    desc: Attend que le cluster soit prêt
    cmds:
      - kubectl wait --for=condition=Ready nodes --all --timeout=300s
      - kubectl wait --for=condition=Ready pods -n kube-system -l k8s-app=kube-dns --timeout=300s
      - sleep 5
    internal: true

  install-ingress-nginx:
    desc: Installe le contrôleur d'ingress NGINX
    cmds:
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - helm repo update
      - |
        helm install ingress-nginx ingress-nginx/ingress-nginx -n ingress-nginx --create-namespace \
          --set controller.hostPort.enabled=true \
          --set controller.hostPort.ports.http=80 \
          --set controller.hostPort.ports.https=443
      - kubectl -n ingress-nginx wait --for=condition=Available deployment/ingress-nginx-controller
    internal: true

  deploy-app:
    desc: Déploie l'application dans le cluster
    cmds:
      - kubectl create namespace demo --dry-run=client -o yaml | kubectl apply -f - --validate=false
      - kubectl -n demo create secret generic db-app --from-literal $"uri=($DATABASE_URL)"
      - helm install todolist ./charts/todolist -n demo
    internal: true
