apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: todolist
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todolist
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: todolist
          image: ghcr.io/naqa92/todolist:latest
          name: todolist
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: todolist
  name: todolist
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app.kubernetes.io/name: todolist
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: todolist
  name: todolist
spec:
  ingressClassName: nginx
  rules:
    - host: todolist.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              service:
                name: todolist
                port:
                  number: 5000
            path: /
            pathType: ImplementationSpecific
