apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: todos
spec:
  credentials:
    scheme: postgres
    port: 5432
    hostFrom:
      secretKeyRef:
        key: host
        name: db-app
    user: neondb_owner
    passwordFrom:
      secretKeyRef:
        key: password
        name: db-app
    database: neondb
    parameters:
      sslmode: require # Requis pour Neon
  schema:
    sql: |
      create table todos (
        id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        title varchar(100) not null,
        complete boolean not null default false
      );
